version: "2"
services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"

  php:
    image: php
    expose:
      - "9000"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
 
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
